language: node_js
node_js: node
deploy: damp-mesa-56372
  provider: heroku
  api_key:
    secure: eW78Kn0r5uvd1bNisZ5h4AhUU2h35i+88dpNM8lna31q1UOstRWzBGzi/VDBHhUaVgfFi4SSv7YUZm/JvfungbtkfKzsCmlUY555uFZiQCnWYiIHNMqROY9MpuaC8JuLcu/kE+JZ0DticGdZWUKalHwrA1u9Q2m9Se9NZ+PGObHp7KLBB4lc8IbC3YD8n0WxjI0WnxIciO1kS40uM82EDyKglmkxb4RZJ7E7BcIJ9EjLzKVnGXZojaQHWdKA4VOovtuSHM0ExszmKJrjCWI7YA9NRu1hP5xIyuOgwmkqCC58yak/PKQV7qr0SzmYKjFe1vEdbmIS/gXexf2TIxCqKoi3yBJsIk5kYVyoFeIqIjROjkebmiQUbhT+ZZZYhaTGnvlQ8Be2xvVN/wnZ674y40hQTfynET6UDxTnBD1cXV60zNT00LKtIz3VFDugeXMaW88H1rNO351MwuVykzD1mIWPiiPNovIem0PPWYgTkQ9J6aFgCggvWOMt0e5labNXfledxPQVs4fSXAUKx62KkP5/PuyxMBvKvs6/3dCnZ6+CvNlYxxWMX6BIA0UHXZOejDfa7FeLZGG9IgLuAhi9BG0tbkk+p9DpEhG3BCe/IH36yZomvsGB1fig8Aztja9LKW8dv7SC9GCu82PUyDgk6sSuzF8JSiIpMKtSyQ9aQLU=
  app: node-shopping-list-integration-tests
  on:
    repo: dwedgeworth/node-shopping-list-integration-tests
